const BOARD_DIMENSIONS = {
  WIDTH: 10,
  HEIGHT: 20,
};

const BOARD_EDGE = {
  LEFT: 0,
  RIGHT: BOARD_DIMENSIONS.WIDTH - 1,
  TOP: 0,
  BOTTOM: BOARD_DIMENSIONS.HEIGHT - 1,
};

export { BOARD_DIMENSIONS, BOARD_EDGE };
