import { Vector } from "$types/typeCollection";

const INITIAL_INTERVAL = 300;
const SPAWN_LOCATION = [-3, 4] as Vector;
const DEFAULT_SPEEDUP_FACTOR = 1;
const ARROW_DOWN_SPEEDUP_FACTOR = 4;
const MIN_INTERVAL = 40;

export {
  INITIAL_INTERVAL,
  SPAWN_LOCATION,
  DEFAULT_SPEEDUP_FACTOR,
  ARROW_DOWN_SPEEDUP_FACTOR,
  MIN_INTERVAL,
};
